### ISSUE TITLE
Nuxt support

### ISSUE THREAD

**Issue by selfagency** [vuedx/languagetools#123]
**Is your feature request related to a problem? Please describe.**
The plugin throws when it encounters the Nuxt component
![image](https://user-images.githubusercontent.com/2541728/103309983-894f9f80-49e4-11eb-95a3-49bb60d6f142.png)

**Describe the solution you'd like**
I mean it'd be awesome if VueDX also debugged Nuxt apps (it doesn't, for example, pick up any of the modules specified in nuxt.config.js) but I'll settle for it at least knowing it's dealing with a Nuxt app so it doesn't throw errors

**Describe alternatives you've considered**
Disabling VueDX

**Comment by znck** [comment]
I see global components are not recognized, I'll fix that soon.  Do you face any other issue?

Until then you define your global components using `vueconfig.json` or `JSX.IntrinsicElements` type.

> Using `vueconfig.json`
```json
{
  "globalComponents": [{
      "Nuxt": {
        "moduleName": "nuxt",
        "exportName": "Nuxt"
      }
    }]
}
```

> Using `JSX.IntrinsicEletments`

```ts
declare namespace JSX {
  interface IntrinsicElements {
    Nuxt: { propName: string }
  }
}
```

cc @Atinux

**Comment by emilsgulbis** [comment]
variables from asyncData are not recognized.
`Property 'article' does not exist on type` when using
```
async asyncData({ $content, params }) {
  const article = await $content('news', params.slug).fetch()
}
```

**Comment by eggsy** [comment]
Nuxt-Link and other Nuxt internal components aren't recognized.

![image](https://user-images.githubusercontent.com/13917975/103626210-ba523780-4ef0-11eb-96f8-f3748ab0931e.png)

Some of the global modules (with prepended name, which is done in nuxt.config.js) is not recognized.

![image](https://user-images.githubusercontent.com/13917975/103626294-d3f37f00-4ef0-11eb-9f29-37f26dc220c5.png)

![image](https://user-images.githubusercontent.com/13917975/103626335-e5d52200-4ef0-11eb-8ba1-60499cb9a447.png)

Prop types of global components (which are auto-imported by Nuxt) showing like this. Though the type checking is fine, it looks weird to see `required: boolean`.

![image](https://user-images.githubusercontent.com/13917975/103626495-203ebf00-4ef1-11eb-868b-d4c2f77c8177.png)

![image](https://user-images.githubusercontent.com/13917975/103627014-df937580-4ef1-11eb-9c85-e1496f8c594f.png)

This HTML attribute, which I use to prevent capital "i" (İ) letter (in Turkish) in English words error because it tries to look it up as a prop type.

![image](https://user-images.githubusercontent.com/13917975/103626573-3cdaf700-4ef1-11eb-81d6-8bd56ea9e06b.png)

And another issue is this saying the component might not be available in runtime, which is not really an issue with Nuxt, never had a problem with a component not being available in the runtime.

![image](https://user-images.githubusercontent.com/13917975/103626704-70b61c80-4ef1-11eb-9357-aef9cc19e657.png)

You can check out [eggsy/eggsy-website@tailwind](https://github.com/eggsy/eggsy-website/tree/tailwind) for the project I got the screenshots from. It's ready to deploy with Nuxt on Netlify and everything is working out of the box. If you need anything, let me know!

**Comment by itpropro** [comment]
Global components (basically all components since Nuxt 2.15/Components v2 https://github.com/nuxt/components/releases/tag/v2.0.0) recognition would be great :slightly_smiling_face:

**Comment by itpropro** [comment]
Any updates on this? I would really really love to use one of my favorite VSCode extensions with my favorite frontend framework ;)

**Comment by znck** [comment]
Not yet. I am exploring a new approach for TS plugin (with some inspiration from volar and angular plugin) which uses only public APIs.
