### ISSUE TITLE
Wrong comments when writing css

### ISSUE THREAD

**Issue by jcenn** [vuedx/languagetools#317]
I found this extension randomly and thought to give it a try but I found a rather infuriating bug.
When I tried to comment a scss line with "ctrl+/" for some reason I was getting html comment symbols instead of the usual css ones
```
What should happen:
// line

What was happening: 
<!-- line -->
```
I was writing Vue 3 code using the composition api with scss (I tested it and I get the same results even without `lang="scss"`)

example component where the bug was occuring between the style tags:
```
<template>
<div class="navbar">
    Navbar
</div>
</template>

<script setup lang="ts">

</script>

<style lang="scss">
    .navbar{
        width: 50vw;
        height: 75px;
        background-color: white;
    }
</style>
```
Disabling the extension fixed everything for me.

**Comment by cfviotti** [comment]
I'd suggest re-opening this issue because I am experiencing the same problem, which seems to be shared by other individuals based on the number of upvotes on this [SO answer](https://stackoverflow.com/a/69130359) and this [duplicate](https://github.com/vuedx/languagetools/issues/211).

In my opinion, the syntax highlighting from this extension is better than Volar’s. However, I still wish to use Volar for its additional features while also being able to quickly comment on style blocks accurately. Unfortunately, this is currently not possible.
